# 04 - Pandas: Series, DataFrames, I/O & Selection

Pandas is the data-wrangling workhorse. Built on NumPy, it adds labeled rows/columns and missing-data handling.

In [1]:
import numpy as np
import pandas as pd
print(pd.__version__)

2.3.3

## 1. Series — a 1D labeled array

In [2]:
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'], name='scores')
print(s)
print('s["b"] =', s['b'])
print('mean :', s.mean())

a    10
b    20
c    30
d    40
Name: scores, dtype: int64
s["b"] = 20
mean : 25.0

## 2. DataFrame — a 2D labeled table

In [3]:
df = pd.DataFrame({
    'name'  : ['Ada', 'Bo', 'Cy', 'Di', 'Eve'],
    'age'   : [29, 35, 41, 22, 31],
    'city'  : ['NYC', 'SF', 'NYC', 'LA', 'SF'],
    'salary': [85_000, 120_000, 95_000, 60_000, 110_000],
})
df

  name  age city  salary
0  Ada   29  NYC   85000
1   Bo   35   SF  120000
2   Cy   41  NYC   95000
3   Di   22   LA   60000
4  Eve   31   SF  110000

In [4]:
# Quick inspection
print(df.shape)
print(df.dtypes)
df.info()
df.describe()

(5, 4)
name      object
age        int64
city      object
salary     int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   city    5 non-null      object
 3   salary  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

             age         salary
count   5.000000       5.000000
mean   31.600000   94000.000000
std     7.056912   23291.629398
min    22.000000   60000.000000
25%    29.000000   85000.000000
50%    31.000000   95000.000000
75%    35.000000  110000.000000
max    41.000000  120000.000000

## 3. Reading & writing files
Pandas reads almost anything: CSV, Excel, Parquet, JSON, SQL, HTML tables.

In [5]:
# Write then read back as a demo
df.to_csv('/tmp/people.csv', index=False)
df2 = pd.read_csv('/tmp/people.csv')
df2

  name  age city  salary
0  Ada   29  NYC   85000
1   Bo   35   SF  120000
2   Cy   41  NYC   95000
3   Di   22   LA   60000
4  Eve   31   SF  110000

**Useful `read_csv` arguments:** `sep`, `header`, `names`, `usecols`, `dtype`, `parse_dates`, `na_values`, `nrows`, `chunksize`.

## 4. Selecting columns and rows
- `df['col']` → Series
- `df[['a','b']]` → DataFrame
- `df.loc[row_label, col_label]` → label-based
- `df.iloc[row_int,  col_int]`  → position-based

In [6]:
print(df['name'])           # Series
print(df[['name', 'city']]) # DataFrame

0    Ada
1     Bo
2     Cy
3     Di
4    Eve
Name: name, dtype: object
  name city
0  Ada  NYC
1   Bo   SF
2   Cy  NYC
3   Di   LA
4  Eve   SF

In [7]:
# Label-based
print(df.loc[0])                       # first row
print(df.loc[0:2, ['name', 'age']])    # inclusive on both ends!

# Position-based
print(df.iloc[0])
print(df.iloc[0:2, 0:2])               # exclusive on the right end

name        Ada
age          29
city        NYC
salary    85000
Name: 0, dtype: object
  name  age
0  Ada   29
1   Bo   35
2   Cy   41
name        Ada
age          29
city        NYC
salary    85000
Name: 0, dtype: object
  name  age
0  Ada   29
1   Bo   35

## 5. Boolean filtering

In [8]:
df[df['age'] > 30]

  name  age city  salary
1   Bo   35   SF  120000
2   Cy   41  NYC   95000
4  Eve   31   SF  110000

In [9]:
# Combine conditions — wrap each in parens, use & and |
df[(df['city'] == 'SF') & (df['salary'] > 100_000)]

  name  age city  salary
1   Bo   35   SF  120000
4  Eve   31   SF  110000

In [10]:
# .query() can read more naturally
df.query('city == "NYC" and age < 40')

  name  age city  salary
0  Ada   29  NYC   85000

## 6. Adding / transforming columns

In [11]:
df['tax']         = df['salary'] * 0.30
df['salary_k']    = df['salary'] / 1000
df['senior']      = df['age'] >= 35
df

  name  age city  salary      tax  salary_k  senior
0  Ada   29  NYC   85000  25500.0      85.0   False
1   Bo   35   SF  120000  36000.0     120.0    True
2   Cy   41  NYC   95000  28500.0      95.0    True
3   Di   22   LA   60000  18000.0      60.0   False
4  Eve   31   SF  110000  33000.0     110.0   False

## Exercises
1. Create a DataFrame of 5 products with columns: `product`, `price`, `units_sold`. Add a `revenue` column.
2. From `df` above, select all people in NYC or LA earning under 100k using `.query()`.
3. Read the CSV back with `pd.read_csv('/tmp/people.csv', usecols=['name','salary'])` and verify only those columns load.